#SPRING CONFIGURATION
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Lisandro
    url: jdbc:mysql://localhost/vaas_financingtool?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB